// *************************************************************************
//
// jc_cordic -- atan2(py, px) for a merged jet, as a binary angle.
//
// Vectoring-mode CORDIC: rotate (x,y) until y reaches zero and accumulate
// the angles used. Chosen over a log-domain ratio because it needs no
// division, no exponential and no large table, and because it treats every
// magnitude the same -- a merged jet's px or py can sit anywhere from the
// pt floor to a TeV.
//
// The rotation table is already in phi's units (radians * 2^32/2pi), so the
// accumulated angle IS the answer -- no final scale, and the 0/2pi seam
// wraps for free on the accumulator's own overflow.
//
// Three things this does beyond the textbook loop:
//
//   Quadrant fold. Vectoring only converges for |angle| <= pi/2, so a
//   negative px has both components negated and pi added afterwards. That
//   is exact in binary angle: pi is 2^31.
//
//   Normalisation. The pt floor puts max(|px|,|py|) near 2^31 in Q14.34
//   integer terms; shifting right by 27 in the last iterations would leave
//   four significant bits. Both inputs are shifted up to the top of the
//   internal word first, which preserves the ratio -- and only the ratio
//   matters for an angle.
//
//   Gain is ignored. CORDIC scales the vector by ~1.647, which would matter
//   if we wanted the magnitude. We do not: pt^2 comes from px^2 + py^2 in
//   jc_setkin, exactly, so only the angle is taken from here.
//
// Iterative, one rotation per cycle: this runs once per merge against about
// a hundred cycles of sweeps, so latency is the cost and an unrolled array
// would buy nothing for 28x the area.
//
// *************************************************************************
`include "jc_defs.vh"
`timescale 1ns/1ps
module jc_cordic (
  input                                start,
  input  signed [`JC_P4_W-1:0]         in_px,
  input  signed [`JC_P4_W-1:0]         in_py,

  output logic                         busy,
  output logic                         done,      // one-cycle pulse
  output logic [`JC_COORD_W-1:0]       out_phi,

  input                                aclk,
  input                                aresetn
);

  localparam int P4_W    = `JC_P4_W;
  localparam int W       = `JC_CORDIC_W;
  localparam int MSB     = `JC_CORDIC_MSB;
  localparam int ITERS   = `JC_CORDIC_ITERS;
  localparam int COORD_W = `JC_COORD_W;

  // Rotation angles, generated by model/gen_luts.py.
  logic [COORD_W-1:0] jc_lut_atan [0:`JC_LUT_ATAN_DEPTH-1];
  `include "jc_luts_cordic.vh"

  localparam logic [1:0] ST_IDLE = 2'd0,
                         ST_NORM = 2'd1,
                         ST_ITER = 2'd2;

  logic        [1:0] state;
  logic signed [W-1:0] x, y;
  logic [COORD_W-1:0]  z;
  logic [COORD_W-1:0]  quad_offset;
  logic  [5:0]         iter;

  // ---- Quadrant fold ----------------------------------------------------
  // Negating both components reflects through the origin, which is a shift
  // of exactly pi -- and pi is 2^31 in binary angle, so the fixup is a
  // constant add that wraps correctly on its own.
  wire fold = in_px[P4_W-1];
  wire signed [P4_W-1:0] fx = fold ? -in_px : in_px;
  wire signed [P4_W-1:0] fy = fold ? -in_py : in_py;

  // ---- Normalisation shift ----------------------------------------------
  // Derived from the LATCHED x and y, not from the input ports. Taking it
  // from the ports would make the shift depend on the caller still driving
  // them a cycle after start, which is an easy contract to break silently.
  wire [W-1:0] abs_x = x[W-1] ? -x : x;
  wire [W-1:0] abs_y = y[W-1] ? -y : y;
  wire [W-1:0] mag   = abs_x | abs_y;

  logic [6:0] lead;
  integer b;
  always_comb begin
    lead = '0;
    for (b = 0; b < W; b = b + 1)
      if (mag[b]) lead = b;
  end
  localparam logic [6:0] MSB7 = MSB;
  wire [6:0] shift = (lead < MSB7) ? (MSB7 - lead) : 7'd0;

  // This iteration's rotation, and where z lands after it. Naming the next
  // value lets the final iteration publish the result in the same cycle it
  // is computed, instead of needing a second driver on out_phi.
  wire [COORD_W-1:0] z_step = jc_lut_atan[iter[4:0]];
  wire [COORD_W-1:0] z_next = y[W-1] ? (z - z_step) : (z + z_step);

  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      state <= ST_IDLE;
      done  <= 1'b0;
      busy  <= 1'b0;
    end
    else begin
      done <= 1'b0;
      case (state)
        ST_IDLE: begin
          if (start) begin
            busy        <= 1'b1;
            quad_offset <= fold ? {1'b1, {(COORD_W-1){1'b0}}} : '0;
            // Sign-extend into the wide word, then normalise next cycle.
            x     <= {{(W-P4_W){fx[P4_W-1]}}, fx};
            y     <= {{(W-P4_W){fy[P4_W-1]}}, fy};
            z     <= '0;
            iter  <= '0;
            state <= ST_NORM;
          end
        end

        ST_NORM: begin
          // px = py = 0 has no angle. jc_setkin guards on pt_sq before
          // starting, so this only protects against a stray request -- but a
          // hang would be much worse than a wrong angle.
          if (mag == {W{1'b0}}) begin
            out_phi <= '0;
            busy    <= 1'b0;
            done    <= 1'b1;
            state   <= ST_IDLE;
          end
          else begin
            x     <= x <<< shift;
            y     <= y <<< shift;
            state <= ST_ITER;
          end
        end

        ST_ITER: begin
          // Vectoring: drive y to zero, accumulating the angle turned.
          if (y[W-1]) begin          // y < 0, rotate the other way
            x <= x - (y >>> iter);
            y <= y + (x >>> iter);
          end
          else begin
            x <= x + (y >>> iter);
            y <= y - (x >>> iter);
          end
          z <= z_next;

          if (iter == ITERS - 1) begin
            state <= ST_IDLE;
            busy  <= 1'b0;
            done  <= 1'b1;
            // Accumulated angle plus the quadrant fixup, wrapping on the
            // adder's own overflow -- exactly right, since a full turn is
            // 2^COORD_W.
            out_phi <= z_next + quad_offset;
          end
          else begin
            iter <= iter + 1'b1;
          end
        end

        default: state <= ST_IDLE;
      endcase
    end
  end

endmodule: jc_cordic
