// *************************************************************************
//
// jc_cordic -- atan2(py, px) for a merged jet, as a binary angle.
//
// Vectoring-mode CORDIC: rotate (x,y) until y reaches zero and accumulate
// the angles used. Chosen over a log-domain ratio because it needs no
// division, no exponential and no large table, and because it treats every
// magnitude the same -- a merged jet's px or py can sit anywhere from the
// pt floor to a TeV.
//
// The rotation table is already in phi's units (radians * 2^32/2pi), so the
// accumulated angle IS the answer -- no final scale, and the 0/2pi seam
// wraps for free on the accumulator's own overflow.
//
// Three things this does beyond the textbook loop:
//
//   Quadrant fold. Vectoring only converges for |angle| <= pi/2, so a
//   negative px has both components negated and pi added afterwards. That
//   is exact in binary angle: pi is 2^31.
//
//   Normalisation. The pt floor puts max(|px|,|py|) near 2^31 in Q14.34
//   integer terms; shifting right by 27 in the last iterations would leave
//   four significant bits. Both inputs are shifted up to the top of the
//   internal word first, which preserves the ratio -- and only the ratio
//   matters for an angle.
//
//   Gain is ignored. CORDIC scales the vector by ~1.647, which would matter
//   if we wanted the magnitude. We do not: pt^2 comes from px^2 + py^2 in
//   jc_setkin, exactly, so only the angle is taken from here.
//
// SPATIALLY UNROLLED, TWO ROTATIONS PER PIPELINE STAGE. It was a 28-cycle
// serial loop, and the loop was the whole problem. With a running `iter` the
// shift `y >>> iter` is a VARIABLE shift -- a 56-bit barrel shifter inside
// the feedback path, 18 logic levels, and the worst path in the entire plugin
// both out of context and in jet_v3's routed report. Unrolled, every shift
// amount is a compile-time constant, so all 28 barrel shifters collapse into
// wiring and each stage is two plain add/subs deep.
//
// So this is not the area-for-speed trade the textbook describes. It is
// cheaper per rotation than the loop was, and it costs ~14 cycles of latency
// out of a ~34-cycle merge. The old comment here claimed an unrolled array
// "would buy nothing for 28x the area" -- that was wrong on both counts: the
// variable shifters were most of the area, and jc_setkin waits on this.
//
// Latency: 1 (latch) + 2 (normalise) + STAGES (rotate) + 1 (publish).
// At ITERS=28 that is 18 cycles, against 30 before. Going lower buys nothing:
// jc_setkin's own log/rapidity chain is 18 cycles and the MARK sweep it runs
// under is 19, so this is no longer what the round waits for.
//
// THE ARITHMETIC IS UNCHANGED, deliberately and to the bit. Same recurrence,
// same order, same widths, same truncating shifts -- only the register
// boundaries moved. model/jc_exact.py replicates this loop bit-for-bit and
// needs no change; test_jc_cordic must stay bit-identical, not merely close.
//
// *************************************************************************
`include "jc_defs.vh"
`timescale 1ns/1ps
module jc_cordic (
  input                                start,
  input  signed [`JC_P4_W-1:0]         in_px,
  input  signed [`JC_P4_W-1:0]         in_py,

  output logic                         busy,
  output logic                         done,      // one-cycle pulse
  output logic [`JC_COORD_W-1:0]       out_phi,

  input                                aclk,
  input                                aresetn
);

  localparam int P4_W    = `JC_P4_W;
  localparam int W       = `JC_CORDIC_W;
  localparam int MSB     = `JC_CORDIC_MSB;
  localparam int ITERS   = `JC_CORDIC_ITERS;
  localparam int COORD_W = `JC_COORD_W;

  // Two rotations per stage, rounding up so an odd ITERS still works -- the
  // spare half-stage is generated away below.
  localparam int STAGES  = (ITERS + 1) / 2;

  // Rotation angles, generated by model/gen_luts.py.
  logic [COORD_W-1:0] jc_lut_atan [0:`JC_LUT_ATAN_DEPTH-1];
  `include "jc_luts_cordic.vh"

  // NORMALISATION IS TWO STATES, and that is a timing result. Finding the
  // leading one is a 56-input priority encoder; applying the shift is a 56-bit
  // variable barrel shifter. In series they were the worst path in the whole
  // plugin once the rotation loop stopped being -- 0.837 ns of slack against
  // the ~0.97 ns this design loses to routing in context, i.e. a miss.
  // Splitting them costs ONE cycle per merge, which the round does not even
  // see: jc_setkin's own log/rapidity chain is 18 cycles and MARK is 19, so
  // the CORDIC has slack to give away here and nothing else does.
  localparam logic [2:0] ST_IDLE  = 3'd0,
                         ST_NORM1 = 3'd1,   // find the leading one
                         ST_NORM2 = 3'd2,   // apply the shift
                         ST_RUN   = 3'd3;

  logic        [2:0]   state;
  logic        [6:0]   shift_r;
  logic signed [W-1:0] x, y;
  logic [COORD_W-1:0]  quad_offset;

  // ---- Quadrant fold ----------------------------------------------------
  // Negating both components reflects through the origin, which is a shift
  // of exactly pi -- and pi is 2^31 in binary angle, so the fixup is a
  // constant add that wraps correctly on its own.
  wire fold = in_px[P4_W-1];
  wire signed [P4_W-1:0] fx = fold ? -in_px : in_px;
  wire signed [P4_W-1:0] fy = fold ? -in_py : in_py;

  // ---- Normalisation shift ----------------------------------------------
  // Derived from the LATCHED x and y, not from the input ports. Taking it
  // from the ports would make the shift depend on the caller still driving
  // them a cycle after start, which is an easy contract to break silently.
  wire [W-1:0] abs_x = x[W-1] ? -x : x;
  wire [W-1:0] abs_y = y[W-1] ? -y : y;
  wire [W-1:0] mag   = abs_x | abs_y;

  logic [6:0] lead;
  integer b;
  always_comb begin
    lead = '0;
    for (b = 0; b < W; b = b + 1)
      if (mag[b]) lead = b;
  end
  localparam logic [6:0] MSB7 = MSB;
  wire [6:0] shift = (lead < MSB7) ? (MSB7 - lead) : 7'd0;

  // ---- The rotation pipeline --------------------------------------------
  // Flat packed vectors with part-selects rather than unpacked arrays: an
  // unpacked array element read through a continuous assign is the construct
  // that silently stopped propagating inside jc_sweep's elaboration (CLAUDE.md
  // trap 3). Slot k is the value entering stage k; slot STAGES is the result.
  logic [(STAGES+1)*W-1:0]       p_x, p_y;
  logic [(STAGES+1)*COORD_W-1:0] p_z, p_off;
  logic [STAGES:0]               p_v;

  genvar gk;
  generate
    for (gk = 0; gk < STAGES; gk = gk + 1) begin : g_rot
      localparam int I0 = 2 * gk;
      localparam int I1 = 2 * gk + 1;

      wire signed [W-1:0] x0 = $signed(p_x[gk*W +: W]);
      wire signed [W-1:0] y0 = $signed(p_y[gk*W +: W]);

      // First rotation. Both updates read the PRE-rotation x and y, which is
      // what non-blocking assignment gave in the serial version.
      wire neg0 = y0[W-1];
      wire signed [W-1:0] x1 = neg0 ? (x0 - (y0 >>> I0)) : (x0 + (y0 >>> I0));
      wire signed [W-1:0] y1 = neg0 ? (y0 + (x0 >>> I0)) : (y0 - (x0 >>> I0));

      // Second rotation, chained combinationally in the same stage. Guarded
      // so an odd ITERS generates a single-rotation final stage.
      wire neg1 = (I1 < ITERS) ? y1[W-1] : 1'b0;
      wire signed [W-1:0] x2 = (I1 >= ITERS) ? x1
                             : neg1 ? (x1 - (y1 >>> I1)) : (x1 + (y1 >>> I1));
      wire signed [W-1:0] y2 = (I1 >= ITERS) ? y1
                             : neg1 ? (y1 + (x1 >>> I1)) : (y1 - (x1 >>> I1));

      always_ff @(posedge aclk) begin
        // The angle table is read procedurally, not through a continuous
        // assign, for the same trap-3 reason as the part-selects above.
        logic [COORD_W-1:0] z0, z1;
        z0 = p_z[gk*COORD_W +: COORD_W];
        z1 = neg0 ? (z0 - jc_lut_atan[I0]) : (z0 + jc_lut_atan[I0]);
        if (I1 < ITERS)
          z1 = neg1 ? (z1 - jc_lut_atan[I1]) : (z1 + jc_lut_atan[I1]);

        p_x[(gk+1)*W +: W]             <= x2;
        p_y[(gk+1)*W +: W]             <= y2;
        p_z[(gk+1)*COORD_W +: COORD_W] <= z1;
        p_off[(gk+1)*COORD_W +: COORD_W] <= p_off[gk*COORD_W +: COORD_W];
      end
    end
  endgenerate

  // Valid is the only thing that needs a reset -- the datapath registers are
  // don't-care until a valid reaches them.
  always_ff @(posedge aclk) begin
    if (!aresetn) p_v[STAGES:1] <= '0;
    else          p_v[STAGES:1] <= p_v[STAGES-1:0];
  end

  // ---- Front end and result --------------------------------------------
  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      state  <= ST_IDLE;
      done   <= 1'b0;
      busy   <= 1'b0;
      p_v[0] <= 1'b0;
    end
    else begin
      done   <= 1'b0;
      p_v[0] <= 1'b0;

      case (state)
        ST_IDLE: begin
          if (start) begin
            busy        <= 1'b1;
            quad_offset <= fold ? {1'b1, {(COORD_W-1){1'b0}}} : '0;
            // Sign-extend into the wide word, then normalise next cycle.
            x     <= {{(W-P4_W){fx[P4_W-1]}}, fx};
            y     <= {{(W-P4_W){fy[P4_W-1]}}, fy};
            state <= ST_NORM1;
          end
        end

        // The encoder, on its own. `shift` is derived from the LATCHED x and y
        // rather than the input ports -- taking it from the ports would make
        // it depend on the caller still driving them, and would also hide this
        // path from out-of-context synthesis, which times no path touching a
        // port (trap 5). It is the path that matters, so it must stay visible.
        ST_NORM1: begin
          // px = py = 0 has no angle. jc_setkin guards on pt_sq before
          // starting, so this only protects against a stray request -- but a
          // hang would be much worse than a wrong angle.
          if (mag == {W{1'b0}}) begin
            out_phi <= '0;
            busy    <= 1'b0;
            done    <= 1'b1;
            state   <= ST_IDLE;
          end
          else begin
            shift_r <= shift;
            state   <= ST_NORM2;
          end
        end

        // The shifter, on its own, off a registered shift amount.
        ST_NORM2: begin
          p_x[0 +: W]         <= x <<< shift_r;
          p_y[0 +: W]         <= y <<< shift_r;
          p_z[0 +: COORD_W]   <= '0;
          p_off[0 +: COORD_W] <= quad_offset;
          p_v[0]              <= 1'b1;
          state               <= ST_RUN;
        end

        ST_RUN: begin
          if (p_v[STAGES]) begin
            // Accumulated angle plus the quadrant fixup, wrapping on the
            // adder's own overflow -- exactly right, since a full turn is
            // 2^COORD_W.
            out_phi <= p_z[STAGES*COORD_W +: COORD_W]
                     + p_off[STAGES*COORD_W +: COORD_W];
            busy    <= 1'b0;
            done    <= 1'b1;
            state   <= ST_IDLE;
          end
        end

        default: state <= ST_IDLE;
      endcase
    end
  end

endmodule: jc_cordic
