// *************************************************************************
//
// jc_log2 -- integer log2, the engine's only logarithm.
//
// Every log in the design goes through here: the beam weight and the
// rapidity in jc_setkin, and the nn_dist_log refresh for rows jc_sweep's
// write-back claimed. Concentrating them is what lets the 16 replicated
// distance lanes stay pure geometry -- a log per lane would have cost
// roughly 16 DSPs and thousands of LUTs per engine for something used a
// handful of times per merge.
//
//   log2(x) = e + log2(m),  e = position of the leading one, m in [1,2)
//
// e is a priority encode; log2(m) is a table on the top JC_LOG2_IDX_BITS
// mantissa bits with linear interpolation over the next JC_LOG2_FRAC_BITS.
//
// The table holds 2^k + 1 entries so interpolation reads i and i+1 from a
// true dual-port BRAM and subtracts, rather than storing a second slope
// table. Entries are Q1.31 because the last one is log2(2) = 1.0, which
// does not fit in Q0.32.
//
// Result is the log of the INTEGER x. A caller holding a fixed-point value
// subtracts its own fractional bit count -- keeping this unit format-free
// is what lets one instance serve Q28.68 products, Q15.34 sums and the raw
// JC_GEO_W distances without a mode input.
//
// Fixed 6-cycle latency, no handshake; x = 0 raises `zero` and returns 0,
// because there is no representable answer and the callers all have a
// meaningful substitute (the beam, or a sentinel).
//
// The sixth cycle is a timing stage, not arithmetic. Reading the table,
// subtracting its two neighbours, multiplying by the fraction and adding the
// base back was one cycle, and it measured 3.970 ns -- 251 MHz out of
// context, which is +0.020 ns of nothing once a shell surrounds it. The
// subtract now has its own stage; the interpolation is otherwise untouched.
//
// jc_setkin's LOG_LAT tracks this depth and must move with it. Nothing else
// does: jc_ctrl borrows the unit through a valid/ready handshake and counts
// no cycles.
//
// *************************************************************************
`include "jc_defs.vh"
`timescale 1ns/1ps
module jc_log2 (
  input                              in_valid,
  input  [`JC_LOG2_IN_W-1:0]         in_x,

  output logic                       out_valid,
  output logic                       out_zero,
  output logic [`JC_LOG2_OUT_W-1:0]  out_log2,

  input                              aclk,
  input                              aresetn
);

  localparam int IN_W     = `JC_LOG2_IN_W;
  localparam int IDX_BITS = `JC_LOG2_IDX_BITS;
  localparam int FRC_BITS = `JC_LOG2_FRAC_BITS;
  localparam int TAB_W    = `JC_LOG2_TAB_W;
  localparam int TAB_FRAC = `JC_LOG2_TAB_FRAC;
  localparam int EXP_W    = `JC_LOG2_EXP_W;
  localparam int OUT_W    = `JC_LOG2_OUT_W;
  localparam int OUT_FRAC = `JC_LOG2_OUT_FRAC;

  localparam int MANT_W = IDX_BITS + FRC_BITS;

  // The table, generated by model/gen_luts.py.
  logic [TAB_W-1:0] jc_lut_log2m [0:`JC_LOG2_DEPTH-1];
  `include "jc_luts_log2.vh"

  // ---- Stage 1: leading-one position ------------------------------------
  logic [EXP_W-1:0]  e_s1;
  logic [IN_W-1:0]   x_s1;
  logic              zero_s1, valid_s1;

  integer b;
  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      valid_s1 <= 1'b0;
    end
    else begin
      valid_s1 <= in_valid;
      x_s1     <= in_x;
      zero_s1  <= (in_x == {IN_W{1'b0}});
      e_s1     <= '0;
      for (b = 0; b < IN_W; b = b + 1)
        if (in_x[b]) e_s1 <= b[EXP_W-1:0];
    end
  end

  // ---- Stage 2: normalise -----------------------------------------------
  // Shift the leading one up to bit IN_W-1, then the MANT_W bits below it
  // are the mantissa fraction. A left shift by (IN_W-1-e) is the same as a
  // right shift by e of a value pre-aligned to the top, but stated this way
  // it needs no extra width.
  logic [MANT_W-1:0] mant_s2;
  logic [EXP_W-1:0]  e_s2;
  logic              zero_s2, valid_s2;

  wire [IN_W-1:0] norm_s1 = x_s1 << (IN_W-1 - e_s1);

  always_ff @(posedge aclk) begin
    if (!aresetn) valid_s2 <= 1'b0;
    else begin
      valid_s2 <= valid_s1;
      e_s2     <= e_s1;
      zero_s2  <= zero_s1;
      mant_s2  <= norm_s1[IN_W-2 -: MANT_W];
    end
  end

  // ---- Stage 3: table read, both neighbours -----------------------------
  wire [IDX_BITS-1:0] idx_s2 = mant_s2[MANT_W-1 -: IDX_BITS];
  wire [FRC_BITS-1:0] frc_s2 = mant_s2[FRC_BITS-1:0];

  logic [TAB_W-1:0]   tab_lo_s3, tab_hi_s3;
  logic [FRC_BITS-1:0] frc_s3;
  logic [EXP_W-1:0]   e_s3;
  logic               zero_s3, valid_s3;

  always_ff @(posedge aclk) begin
    if (!aresetn) valid_s3 <= 1'b0;
    else begin
      valid_s3  <= valid_s2;
      e_s3      <= e_s2;
      zero_s3   <= zero_s2;
      frc_s3    <= frc_s2;
      tab_lo_s3 <= jc_lut_log2m[idx_s2];
      tab_hi_s3 <= jc_lut_log2m[idx_s2 + 1'b1];
    end
  end

  // ---- Stage 3b: the table difference -----------------------------------
  // Split out so the multiply below starts from a register rather than from
  // the BRAM output through a 32-bit subtract. tab_lo rides along because the
  // final add still needs it.
  logic [TAB_W-1:0]    slope_s3b, tab_lo_s3b;
  logic [FRC_BITS-1:0] frc_s3b;
  logic [EXP_W-1:0]    e_s3b;
  logic                zero_s3b, valid_s3b;

  always_ff @(posedge aclk) begin
    if (!aresetn) valid_s3b <= 1'b0;
    else begin
      valid_s3b  <= valid_s3;
      e_s3b      <= e_s3;
      zero_s3b   <= zero_s3;
      frc_s3b    <= frc_s3;
      tab_lo_s3b <= tab_lo_s3;
      slope_s3b  <= tab_hi_s3 - tab_lo_s3;
    end
  end

  // ---- Stage 4: interpolate ---------------------------------------------
  // slope is one table step, at most log2(1+2^-k) ~ 3.5e-4, so the product
  // with the fraction stays small; this is the unit's only multiply.
  wire [TAB_W+FRC_BITS-1:0] step_s3b = slope_s3b * frc_s3b;

  logic [TAB_W-1:0] mant_log_s4;
  logic [EXP_W-1:0] e_s4;
  logic             zero_s4, valid_s4;

  always_ff @(posedge aclk) begin
    if (!aresetn) valid_s4 <= 1'b0;
    else begin
      valid_s4    <= valid_s3b;
      e_s4        <= e_s3b;
      zero_s4     <= zero_s3b;
      mant_log_s4 <= tab_lo_s3b + step_s3b[TAB_W+FRC_BITS-1 -: TAB_W];
    end
  end

  // ---- Stage 5: assemble -------------------------------------------------
  // Table entries are Q1.31 and the output is Q7.32, so the mantissa term
  // shifts up by one to line up.
  always_ff @(posedge aclk) begin
    if (!aresetn) begin
      out_valid <= 1'b0;
      out_zero  <= 1'b0;
      out_log2  <= '0;
    end
    else begin
      out_valid <= valid_s4;
      out_zero  <= zero_s4;
      out_log2  <= zero_s4
                 ? {OUT_W{1'b0}}
                 : ({{(OUT_W-EXP_W){1'b0}}, e_s4} << OUT_FRAC)
                   + {{(OUT_W-TAB_W-1){1'b0}},
                      mant_log_s4, {(OUT_FRAC-TAB_FRAC){1'b0}}};
    end
  end

endmodule: jc_log2
